import fetch from "node-fetch";
import { getMoodConfig } from "../config/moodConfig.js";

const SPOTIFY_TOKEN_URL = "https://accounts.spotify.com/api/token";
const SPOTIFY_API_BASE = "https://api.spotify.com/v1";

/**
 * Exchange auth code for access + refresh tokens (Authorization Code Flow)
 */
export async function exchangeCode(code, redirectUri) {
  const credentials = Buffer.from(
    `${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`,
  ).toString("base64");

  const response = await fetch(SPOTIFY_TOKEN_URL, {
    method: "POST",
    headers: {
      Authorization: `Basic ${credentials}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      code,
      redirect_uri: redirectUri || process.env.SPOTIFY_REDIRECT_URI,
    }),
  });

  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.error_description || "Spotify token exchange failed");
  }

  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token,
    expiresIn: data.expires_in,
    tokenType: data.token_type,
    scope: data.scope,
    expiresAt: Date.now() + data.expires_in * 1000,
  };
}

/**
 * Refresh an expired access token
 */
export async function refreshAccessToken(refreshToken) {
  const credentials = Buffer.from(
    `${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`,
  ).toString("base64");

  const response = await fetch(SPOTIFY_TOKEN_URL, {
    method: "POST",
    headers: {
      Authorization: `Basic ${credentials}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      grant_type: "refresh_token",
      refresh_token: refreshToken,
    }),
  });

  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.error_description || "Token refresh failed");
  }

  return {
    accessToken: data.access_token,
    expiresIn: data.expires_in,
    expiresAt: Date.now() + data.expires_in * 1000,
    // Spotify sometimes returns a new refresh token
    refreshToken: data.refresh_token || refreshToken,
  };
}

/**
 * Search Spotify tracks by mood query
 */
export async function searchTracksByMood(mood, accessToken, limit = 20) {
  const config = getMoodConfig(mood);
  const query = encodeURIComponent(config.spotifyQuery);

  const response = await fetch(
    `${SPOTIFY_API_BASE}/search?q=${query}&type=track&limit=${limit}&market=US`,
    {
      headers: { Authorization: `Bearer ${accessToken}` },
    },
  );

  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.error?.message || "Spotify search failed");
  }

  return data.tracks?.items || [];
}

/**
 * Get Spotify recommendations based on mood audio features
 */
export async function getRecommendationsByMood(mood, accessToken, limit = 20) {
  const config = getMoodConfig(mood);
  const { seeds } = config;

  const params = new URLSearchParams({
    limit,
    market: "US",
    ...seeds,
  });

  const response = await fetch(
    `${SPOTIFY_API_BASE}/recommendations?${params}`,
    {
      headers: { Authorization: `Bearer ${accessToken}` },
    },
  );

  const data = await response.json();

  if (!response.ok) {
    // Fallback to search if recommendations fail
    console.warn(
      "Recommendations failed, falling back to search:",
      data.error?.message,
    );
    return searchTracksByMood(mood, accessToken, limit);
  }

  return data.tracks || [];
}

/**
 * Get current user's Spotify profile
 */
export async function getSpotifyProfile(accessToken) {
  const response = await fetch(`${SPOTIFY_API_BASE}/me`, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.error?.message || "Failed to fetch Spotify profile");
  }

  return data;
}

/**
 * Create a playlist on user's Spotify account
 */
export async function createSpotifyPlaylist(
  userId,
  playlistName,
  trackUris,
  accessToken,
) {
  // Create playlist
  const createRes = await fetch(
    `${SPOTIFY_API_BASE}/users/${userId}/playlists`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: playlistName,
        description: `Generated by Vibzfy 🎵 – Your mood, your vibe.`,
        public: false,
      }),
    },
  );

  const playlist = await createRes.json();
  if (!createRes.ok)
    throw new Error(playlist.error?.message || "Failed to create playlist");

  // Add tracks
  if (trackUris.length > 0) {
    await fetch(`${SPOTIFY_API_BASE}/playlists/${playlist.id}/tracks`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ uris: trackUris }),
    });
  }

  return playlist;
}
