import fetch from "node-fetch";
import { getMoodConfig } from "../config/moodConfig.js";

const SPOTIFY_TOKEN_URL = "https://accounts.spotify.com/api/token";
const SPOTIFY_API_BASE = "https://api.spotify.com/v1";

// Safe JSON parser – avoids crashes on empty Spotify responses
async function parseJSON(response) {
  const text = await response.text();
  if (!text || text.trim() === "") {
    throw new Error("Empty response from Spotify");
  }
  try {
    return JSON.parse(text);
  } catch {
    throw new Error(`Invalid JSON from Spotify: ${text.slice(0, 100)}`);
  }
}

/**
 * Exchange auth code for access + refresh tokens
 */
export async function exchangeCode(code, redirectUri) {
  const credentials = Buffer.from(
    `${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`,
  ).toString("base64");

  const response = await fetch(SPOTIFY_TOKEN_URL, {
    method: "POST",
    headers: {
      Authorization: `Basic ${credentials}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      code,
      redirect_uri: redirectUri || process.env.SPOTIFY_REDIRECT_URI,
    }),
  });

  const data = await parseJSON(response);

  if (!response.ok) {
    throw new Error(data.error_description || "Spotify token exchange failed");
  }

  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token,
    expiresIn: data.expires_in,
    tokenType: data.token_type,
    scope: data.scope,
    expiresAt: Date.now() + data.expires_in * 1000,
  };
}

/**
 * Refresh an expired access token
 */
export async function refreshAccessToken(refreshToken) {
  const credentials = Buffer.from(
    `${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`,
  ).toString("base64");

  const response = await fetch(SPOTIFY_TOKEN_URL, {
    method: "POST",
    headers: {
      Authorization: `Basic ${credentials}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      grant_type: "refresh_token",
      refresh_token: refreshToken,
    }),
  });

  const data = await parseJSON(response);

  if (!response.ok) {
    throw new Error(data.error_description || "Token refresh failed");
  }

  return {
    accessToken: data.access_token,
    expiresIn: data.expires_in,
    expiresAt: Date.now() + data.expires_in * 1000,
    refreshToken: data.refresh_token || refreshToken,
  };
}

/**
 * Search Spotify tracks by mood query
 * Spotify search limit must be 1–50
 */
export async function searchTracksByMood(mood, accessToken, limit) {
  const config = getMoodConfig(mood);

  // Strict, multi-layered integer verification
  let parsedLimit = parseInt(limit, 10);

  if (isNaN(parsedLimit)) {
    parsedLimit = 20; // Explicit fallback if front-end sends "" or undefined
  } else {
    parsedLimit = Math.min(50, Math.max(1, parsedLimit));
  }

  const query = encodeURIComponent(config.spotifyQuery);

  const response = await fetch(
    `${SPOTIFY_API_BASE}/search?q=${query}&type=track&limit=${parsedLimit}&market=US`,
    {
      headers: { Authorization: `Bearer ${accessToken}` },
    },
  );

  const data = await parseJSON(response);

  if (!response.ok) {
    console.error("Spotify search error full response:", JSON.stringify(data));
    throw new Error(data.error?.message || "Spotify search failed");
  }

  return data.tracks?.items || [];
}

/**
 * Get mood-based tracks (search-based, recommendations API deprecated Nov 2024)
 */
export async function getRecommendationsByMood(mood, accessToken, limit) {
  return searchTracksByMood(mood, accessToken, limit);
}

/**
 * Get current user's Spotify profile
 */
export async function getSpotifyProfile(accessToken) {
  const response = await fetch(`${SPOTIFY_API_BASE}/me`, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  const data = await parseJSON(response);

  if (!response.ok) {
    throw new Error(data.error?.message || "Failed to fetch Spotify profile");
  }

  return data;
}

/**
 * Create a playlist on the user's Spotify account and add tracks
 */
export async function createSpotifyPlaylist(
  userId,
  playlistName,
  trackUris,
  accessToken,
) {
  const createRes = await fetch(
    `${SPOTIFY_API_BASE}/users/${userId}/playlists`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: playlistName,
        description: "Generated by Vibzfy 🎵 – Your mood, your vibe.",
        public: false,
      }),
    },
  );

  const playlist = await parseJSON(createRes);
  if (!createRes.ok) {
    throw new Error(playlist.error?.message || "Failed to create playlist");
  }

  if (trackUris.length > 0) {
    await fetch(`${SPOTIFY_API_BASE}/playlists/${playlist.id}/tracks`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ uris: trackUris }),
    });
  }

  return playlist;
}
