import fetch from "node-fetch";
import { getMoodConfig } from "../config/moodConfig.js";

const SPOTIFY_TOKEN_URL = "https://accounts.spotify.com/api/token";
const SPOTIFY_API_BASE = "https://api.spotify.com/v1";

async function parseJSON(response) {
  const text = await response.text();
  if (!text || text.trim() === "")
    throw new Error("Empty response from Spotify");
  try {
    return JSON.parse(text);
  } catch {
    throw new Error("Invalid JSON from Spotify: " + text.slice(0, 100));
  }
}

export async function exchangeCode(code, redirectUri) {
  const credentials = Buffer.from(
    `${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`,
  ).toString("base64");

  const response = await fetch(SPOTIFY_TOKEN_URL, {
    method: "POST",
    headers: {
      Authorization: `Basic ${credentials}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      code,
      redirect_uri: redirectUri || process.env.SPOTIFY_REDIRECT_URI,
    }),
  });

  const data = await parseJSON(response);
  if (!response.ok)
    throw new Error(data.error_description || "Token exchange failed");

  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token,
    expiresIn: data.expires_in,
    tokenType: data.token_type,
    scope: data.scope,
    expiresAt: Date.now() + data.expires_in * 1000,
  };
}

export async function refreshAccessToken(refreshToken) {
  const credentials = Buffer.from(
    `${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`,
  ).toString("base64");

  const response = await fetch(SPOTIFY_TOKEN_URL, {
    method: "POST",
    headers: {
      Authorization: `Basic ${credentials}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      grant_type: "refresh_token",
      refresh_token: refreshToken,
    }),
  });

  const data = await parseJSON(response);
  if (!response.ok)
    throw new Error(data.error_description || "Token refresh failed");

  return {
    accessToken: data.access_token,
    expiresIn: data.expires_in,
    expiresAt: Date.now() + data.expires_in * 1000,
    refreshToken: data.refresh_token || refreshToken,
  };
}

async function getArtistTopTracks(artistId, accessToken) {
  const response = await fetch(
    `${SPOTIFY_API_BASE}/artists/${artistId}/top-tracks?market=US`,
    { headers: { Authorization: `Bearer ${accessToken}` } },
  );
  const data = await parseJSON(response);
  if (!response.ok) {
    console.warn(`Failed artist ${artistId}:`, data.error?.message);
    return [];
  }
  return data.tracks || [];
}

export async function searchTracksByMood(mood, accessToken, limit = 20) {
  const config = getMoodConfig(mood);
  const artistIds = config.artistIds;

  if (!artistIds || artistIds.length === 0) {
    throw new Error(`No artist IDs for mood: ${mood}`);
  }

  console.log(
    `[${mood}] Fetching top tracks for ${artistIds.length} artists...`,
  );

  const results = await Promise.all(
    artistIds.map((id) => getArtistTopTracks(id, accessToken)),
  );

  const seen = new Set();
  const tracks = [];

  for (const artistTracks of results) {
    for (const track of artistTracks) {
      if (!seen.has(track.id) && track.name) {
        seen.add(track.id);
        tracks.push(track);
      }
    }
  }

  // Shuffle
  for (let i = tracks.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [tracks[i], tracks[j]] = [tracks[j], tracks[i]];
  }

  console.log(
    `[${mood}] Got ${tracks.length} tracks, returning ${Math.min(tracks.length, limit)}`,
  );
  return tracks.slice(0, limit);
}

export async function getRecommendationsByMood(mood, accessToken, limit = 20) {
  return searchTracksByMood(mood, accessToken, limit);
}

export async function getSpotifyProfile(accessToken) {
  const response = await fetch(`${SPOTIFY_API_BASE}/me`, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  const data = await parseJSON(response);
  if (!response.ok)
    throw new Error(data.error?.message || "Failed to fetch profile");
  return data;
}

export async function createSpotifyPlaylist(
  userId,
  playlistName,
  trackUris,
  accessToken,
) {
  const createRes = await fetch(
    `${SPOTIFY_API_BASE}/users/${userId}/playlists`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: playlistName,
        description: "Generated by Vibezfy 🎵 – Your mood, your vibe.",
        public: false,
      }),
    },
  );

  const playlist = await parseJSON(createRes);
  if (!createRes.ok)
    throw new Error(playlist.error?.message || "Failed to create playlist");

  if (trackUris.length > 0) {
    await fetch(`${SPOTIFY_API_BASE}/playlists/${playlist.id}/tracks`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ uris: trackUris }),
    });
  }

  return playlist;
}
