export const MOOD_CONFIG = {
  happy: {
    label: "Happy",
    emoji: "😊",
    gradient: "from-amber-400 via-orange-300 to-yellow-200",
    glowColor: "rgba(251,191,36,0.4)",
    primaryColor: "#FFB347",
    secondaryColor: "#FF6B35",
    ambientScene: "golden_hour",
    ambientDesc: "Golden Hour City",
    playlistName: "☀️ Sunny Afternoon Lo-Fi",
    bgClass: "from-amber-900/20 to-orange-900/10",
    accentClass: "text-amber-400",
    borderClass: "border-amber-500/30",
  },
  sad: {
    label: "Sad",
    emoji: "😢",
    gradient: "from-blue-600 via-blue-400 to-slate-300",
    glowColor: "rgba(96,165,250,0.4)",
    primaryColor: "#4A90B8",
    secondaryColor: "#2C5F7A",
    ambientScene: "rain_cafe",
    ambientDesc: "Rainy Café Window",
    playlistName: "🌧️ Rainy Day Lo-Fi",
    bgClass: "from-blue-900/20 to-slate-900/10",
    accentClass: "text-blue-400",
    borderClass: "border-blue-500/30",
  },
  angry: {
    label: "Angry",
    emoji: "😠",
    gradient: "from-red-800 via-red-600 to-orange-500",
    glowColor: "rgba(239,68,68,0.4)",
    primaryColor: "#8B0000",
    secondaryColor: "#FF4500",
    ambientScene: "stormy_night",
    ambientDesc: "Stormy Night Sky",
    playlistName: "⚡ Dark Lo-Fi Storm",
    bgClass: "from-red-900/20 to-orange-900/10",
    accentClass: "text-red-400",
    borderClass: "border-red-500/30",
  },
  fearful: {
    label: "Anxious",
    emoji: "😨",
    gradient: "from-green-700 via-emerald-500 to-teal-300",
    glowColor: "rgba(52,211,153,0.4)",
    primaryColor: "#228B22",
    secondaryColor: "#90EE90",
    ambientScene: "misty_forest",
    ambientDesc: "Misty Morning Forest",
    playlistName: "🌿 Calm Forest Ambient",
    bgClass: "from-green-900/20 to-teal-900/10",
    accentClass: "text-emerald-400",
    borderClass: "border-emerald-500/30",
  },
  disgusted: {
    label: "Mellow",
    emoji: "😒",
    gradient: "from-cyan-700 via-teal-500 to-sky-300",
    glowColor: "rgba(20,184,166,0.4)",
    primaryColor: "#006994",
    secondaryColor: "#00CED1",
    ambientScene: "ocean_waves",
    ambientDesc: "Deep Ocean Drift",
    playlistName: "🌊 Ocean Chill Lo-Fi",
    bgClass: "from-cyan-900/20 to-teal-900/10",
    accentClass: "text-cyan-400",
    borderClass: "border-cyan-500/30",
  },
  surprised: {
    label: "Surprised",
    emoji: "😲",
    gradient: "from-purple-700 via-violet-500 to-pink-400",
    glowColor: "rgba(167,139,250,0.4)",
    primaryColor: "#7B2FBE",
    secondaryColor: "#00FF88",
    ambientScene: "northern_lights",
    ambientDesc: "Northern Lights",
    playlistName: "🌌 Euphoric Lo-Fi Aurora",
    bgClass: "from-purple-900/20 to-pink-900/10",
    accentClass: "text-violet-400",
    borderClass: "border-violet-500/30",
  },
  neutral: {
    label: "Focused",
    emoji: "😐",
    gradient: "from-amber-800 via-yellow-600 to-amber-300",
    glowColor: "rgba(217,119,6,0.4)",
    primaryColor: "#8B6914",
    secondaryColor: "#D4A853",
    ambientScene: "cozy_library",
    ambientDesc: "Cozy Library",
    playlistName: "📚 Study Beats Lo-Fi",
    bgClass: "from-amber-900/20 to-yellow-900/10",
    accentClass: "text-amber-400",
    borderClass: "border-amber-500/30",
  },
};

export function getMoodConfig(mood) {
  return MOOD_CONFIG[mood] || MOOD_CONFIG.neutral;
}

export const ALL_MOODS = Object.keys(MOOD_CONFIG);
